<a href="https://colab.research.google.com/github/majorquev/DBDC_202307_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [4]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista

# Podemos guardar los objetos en slots con nombres
l1 <- list(num = 10,
           letra = letters,
           pl = c(T,F,F),
           mat = diag(c(1,2,3)),
           lista = list(a = 1:3, b = "hola buen día"))
# Podemos guardar los objetos en slots sin nombres
l2 <- list(c(1,2), "Mabel")


In [2]:
l1

$num
[1] 10

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$pl
[1]  TRUE FALSE FALSE

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$lista
$lista$a
[1] 1 2 3

$lista$b
[1] "hola buen día"

In [5]:
l2

[[1]]
[1] 1 2

[[2]]
[1] "Mabel"

In [6]:
str(l2)

List of 2
 $ : num [1:2] 1 2
 $ : chr "Mabel"


In [3]:
# estructura
str(l1)

List of 5
 $ num  : num 10
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ pl   : logi [1:3] TRUE FALSE FALSE
 $ mat  : num [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ a: int [1:3] 1 2 3
  ..$ b: chr "hola buen día"


In [8]:
# Podemos combinar listas
l3 <- c(l1,l2)
l3

$num
[1] 10

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$pl
[1]  TRUE FALSE FALSE

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$lista
$lista$a
[1] 1 2 3

$lista$b
[1] "hola buen día"


[[6]]
[1] 1 2

[[7]]
[1] "Mabel"

In [10]:
names(l3)
length(l3)

[1] "num"   "letra" "pl"    "mat"   "lista" ""      ""

[1] 7

In [11]:
# Acceso mediante posición
l3[4] # 4ta entrada


$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [15]:
l3[1]

$num
[1] 10

In [16]:
class(l3[1])

[1] "list"

In [17]:
#si quisièramos las pos 1 y 4
l3[c(1,4)]

$num
[1] 10

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [19]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[[1]]# es el elemento que está en la pos 1. Es decir el 10.
l3[1] # es la lista con el elmento de la pos 1. Es decir list(num = 10)

[1] 10

$num
[1] 10

In [21]:
l3[4]# lista con la matriz
l3[[4]]# matriz

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [22]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ pl   : logi [1:3] TRUE FALSE FALSE
 $ mat  : num [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ a: int [1:3] 1 2 3
  ..$ b: chr "hola buen día"
 $      : num [1:2] 1 2
 $      : chr "Mabel"


In [24]:
# de la lista l3, quiero e 6t0 elemento del vector llamado "letra" de la segunda posición
l3[[2]][6]# Recordar que l3[[2]] ya es el vector de letras,  ycomo tal basta acceder a su 6to elemtno con el "[6]".

[1] "f"

In [28]:
# Acceder al String "hola buen día" de la primera entrada de la lista "lista" de l3.
l3[[5]] # estamos en la lista llamada "lista"
l3[[5]][2] # retorna una lista con el strnig en b
l3[[5]][[2]] # retorna  el strnig en b ( :) )

$a
[1] 1 2 3

$b
[1] "hola buen día"

$b
[1] "hola buen día"

[1] "hola buen día"

In [29]:
str(l3)

List of 7
 $ num  : num 10
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ pl   : logi [1:3] TRUE FALSE FALSE
 $ mat  : num [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista:List of 2
  ..$ a: int [1:3] 1 2 3
  ..$ b: chr "hola buen día"
 $      : num [1:2] 1 2
 $      : chr "Mabel"


In [31]:
# Acceso mediante nombre
# de la lista l3, quiero e 6t0 elemento del vector llamado "letra" de la segunda posición
l3[["letra"]][6]

[1] "f"

In [33]:
# Acceder al String "hola buen día" de la primera entrada de la lista "lista" de l3.
l3[["lista"]][["b"]]

[1] "hola buen día"

In [35]:
# acceso vía "$"
l3$letra[6] # es lo mismo que l3[["letra"]][6] o l3[[2]][6]




[1] "f"

In [37]:
l3$lista$b # es lo mismo que l3[[5]][[2]] o l3[["lista"]][["b"]]

[1] "hola buen día"

In [40]:
# para saber el largo de la lista/vector
length(l3)
# Para obtener los nombres de la lista
names(l3)
# si quisiéramos renombrar los slots:
names(l3)[c(6,7)] <- c("nuevo6", "nuevo7")
str(l3)

[1] 7

[1] "num"   "letra" "pl"    "mat"   "lista" ""      ""

List of 7
 $ num   : num 10
 $ letra : chr [1:26] "a" "b" "c" "d" ...
 $ pl    : logi [1:3] TRUE FALSE FALSE
 $ mat   : num [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista :List of 2
  ..$ a: int [1:3] 1 2 3
  ..$ b: chr "hola buen día"
 $ nuevo6: num [1:2] 1 2
 $ nuevo7: chr "Mabel"


In [42]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l3[["n8"]] <- LETTERS

In [45]:
l3$n9 <- 50:70

In [46]:
str(l3)

List of 9
 $ num   : num 10
 $ letra : chr [1:26] "a" "b" "c" "d" ...
 $ pl    : logi [1:3] TRUE FALSE FALSE
 $ mat   : num [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ lista :List of 2
  ..$ a: int [1:3] 1 2 3
  ..$ b: chr "hola buen día"
 $ nuevo6: num [1:2] 1 2
 $ nuevo7: chr "Mabel"
 $ n8    : chr [1:26] "A" "B" "C" "D" ...
 $ n9    : int [1:21] 50 51 52 53 54 55 56 57 58 59 ...


In [ ]:
# podemos modificar elementos dentro de un slot



### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [48]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
df <- data.frame(edad = c(25,30,34),
                 nombre = c("Mabel", "Miguel", "Julio"),
                 rut = c("1-2", "3-k", "7-0"))
df

edad nombre rut
1 25   Mabel  1-2
2 30   Miguel 3-k
3 34   Julio  7-0

In [51]:
colnames(df)
names(df)
dim(df)

[1] "edad"   "nombre" "rut"

[1] "edad"   "nombre" "rut"

[1] 3 3

In [53]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df[[2]]
df[["nombre"]]
df$nombre


[1] "Mabel"  "Miguel" "Julio"

[1] "Mabel"  "Miguel" "Julio"

[1] "Mabel"  "Miguel" "Julio"

In [54]:
df["nombre"]# mismo comportamiento que en listas. En vez de entregar una lista con el vector, enrega un dataframe con el vector.

nombre
1 Mabel 
2 Miguel
3 Julio

In [57]:
##  Ganamos acceso como matriz
# segundafila de df
df[2,]

# segunda columna y segunda fila
df[2,2]

# la segunda columna
df[,"nombre"]
df[,2]


edad nombre rut
2 30   Miguel 3-k

[1] "Miguel"

[1] "Mabel"  "Miguel" "Julio"

[1] "Mabel"  "Miguel" "Julio"

In [58]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_mascota <- c(F,F,T)

In [59]:
df

edad nombre rut tiene_mascota
1 25   Mabel  1-2 FALSE        
2 30   Miguel 3-k FALSE        
3 34   Julio  7-0  TRUE

In [62]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3
df[c(1,3)] # pensando como lista
df[,c(1,3)] # pensando como matriz
# Referenciando el nombre de las columnas
df[c("edad","rut")] # pensando como lista
df[,c("edad","rut")] # pensando como matriz

edad rut
1 25   1-2
2 30   3-k
3 34   7-0

edad rut
1 25   1-2
2 30   3-k
3 34   7-0

edad rut
1 25   1-2
2 30   3-k
3 34   7-0

edad rut
1 25   1-2
2 30   3-k
3 34   7-0

In [63]:
# Ahora podemos hacer consultas como las haríamos en vectores o matrices
# Todas filas donde la persona tiene màs edde 25 años

df[df$edad > 25,]

edad nombre rut tiene_mascota
2 30   Miguel 3-k FALSE        
3 34   Julio  7-0  TRUE