<a href="https://colab.research.google.com/github/majorquev/DBDC_202307_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [1]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A


[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [2]:

B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [5]:
# clase y atributo dim
class(B)
typeof(B)
dim(B)

[1] "matrix" "array"

[1] "double"

[1] 2 3

In [7]:
dim(B)[1]# nº de filas.
dim(B)[2]# nº de columnas

[1] 2

[1] 3

In [9]:
nrow(B)
ncol(B)

[1] 2

[1] 3

In [11]:
# Genere dos vectores del mismo largo y forme una matriz.
c1 <- c(1,2,3)
c2 <- c(10,20,40)




In [13]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

C <- cbind(c1,c2)
C

c1 c2
[1,] 1  10
[2,] 2  20
[3,] 3  40

In [15]:
letters
LETTERS

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [17]:
f1 <- LETTERS[1:5]
f2 <- letters[5:1]

D <- rbind(f1,f2)
D

[,1] [,2] [,3] [,4] [,5]
f1 A    B    C    D    E   
f2 e    d    c    b    a

In [21]:
colnames(C)
colnames(D)
rownames(D)

[1] "c1" "c2"

NULL

[1] "f1" "f2"

In [23]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
D
nuevo <- c("X","Y")
cbind(D,nuevo)


[,1] [,2] [,3] [,4] [,5]
f1 A    B    C    D    E   
f2 e    d    c    b    a

nuevo
f1 A B C D E X    
f2 e d c b a Y

In [25]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
D
rbind(D,c("j","k"))


[,1] [,2] [,3] [,4] [,5]
f1 A    B    C    D    E   
f2 e    d    c    b    a

Warning message in rbind(D, c("j", "k")):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3] [,4] [,5]
f1 A    B    C    D    E   
f2 e    d    c    b    a   
   j    k    j    k    j

In [26]:
# función diag para la definición de matrices diagonales
#?diag
diag(c(1,1,2,3))



[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    2    0   
[4,] 0    0    0    3

In [29]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
B
B[2,3]

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

[1] 8

In [33]:
# quiero rescatar el elemento "(2,1)"
C
C[2,1]


c1 c2
[1,] 1  10
[2,] 2  20
[3,] 3  40

c1 
 2

In [34]:

# CUIDADO:No es lo mismo que
B
B[2,3]
# es distinto que
B[c(2,3)]

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

[1] 8

[1] 3 1

In [37]:
# Para acceder a una fila completa (fila 2)
B
B[2,]
# Para acceder a una columna completa (col 3)
B[,3]


[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

[1] 3 5 8

[1] 2 8

In [40]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 5 por un -99 (el 5 de la pos 2,2)
B[2,2] <- -99
B


[,1] [,2] [,3]
[1,] 1      1  2   
[2,] 3    -99  8

In [43]:
# Añadir nombres a las filas
rownames(C) <- c("f1","f2","f3")
C

c1 c2
f1 1  10
f2 2  20
f3 3  40

In [46]:
# Acceso mediante nombres
# Quiero rescatar el 40, de la pos 3,2.
C[3,2]
C["f3","c2"]

# Quiero rescatar la 3ra fila
C["f3",]

[1] 40

[1] 40

c1 c2 
 3 40

In [51]:
# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (1,1) y (3,2) de C
#1: Crear una matriz de 3x2 con TRUE en dichas posiciones y FALSE en las restantes.
C
ind <- cbind(c(T,F,F), c(F,F,T))
ind

c1 c2
f1 1  10
f2 2  20
f3 3  40

[,1]  [,2] 
[1,]  TRUE FALSE
[2,] FALSE FALSE
[3,] FALSE  TRUE

In [50]:
C[ind]

[1]  1 40

In [52]:
# Podemos evaluar las casillas de una matriz mediante sentencias lógicas
C >= 3

c1    c2  
f1 FALSE TRUE
f2 FALSE TRUE
f3  TRUE TRUE

In [53]:
C[C >= 3]

[1]  3 10 20 40

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [55]:
# transponer una matriz
C
t(C)

c1 c2
f1 1  10
f2 2  20
f3 3  40

f1 f2 f3
c1  1  2  3
c2 10 20 40

In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [56]:
A
B

[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

[,1] [,2] [,3]
[1,] 1      1  2   
[2,] 3    -99  8

In [57]:
# Multiplicación de matrices
A * B # multiplicación componente a componente


[,1] [,2] [,3]
[1,] 1       2 10  
[2,] 3    -297 64

In [59]:
C %*% B

[,1] [,2]  [,3]
f1  31   -989  82 
f2  62  -1978 164 
f3 123  -3957 326

In [60]:
# podemos calcular determinantes
# ?det
det(C %*% B)


[1] 0

In [61]:
# Podemos invertir matrices
# ?solve
solve(C %*% B)

ERROR: ignored